DjangoSimple/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('ports.urls')),
    path('admin/', admin.site.urls),
]

ports/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.get_home_view, name='home'),
    path('ports', views.get_ports_view, name='ports'),
    path('add_port', views.add_port_view, name='add_port_view'),
    path('add_port_page', views.add_port_page, name='add_port_page'),
    path('edit_port/<int:id>', views.edit_port, name='edit_port'),
    path('del_port/<int:id>', views.del_port, name='del_port'),
    path('upload_csv_page',views.upload_csv_page,name='upload_csv_page'),
    path('trips', views.get_trips_view, name='trips'),
    path('add_trip', views.add_trip_view, name='add_trip_view'),
    path('add_trip_page', views.add_trip_page, name='add_trip_page'),
    path('edit_trip/<int:id>', views.edit_trip, name='edit_trip'),
    path('del_trip/<int:id>', views.del_trip, name='del_trip'),
    path('plots', views.get_plot_view, name='plots'),

]

ports/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.


class Port(models.Model):
    name = models.CharField(null=False, blank=False,
                            max_length=50, unique=True)
    temp = models.FloatField(null=False, blank=False, validators=[
                             MinValueValidator(-30), MaxValueValidator(30)])
    latitude = models.FloatField(null=False, blank=False, validators=[
                                 MinValueValidator(-180), MaxValueValidator(180)])
    longitude = models.FloatField(null=False, blank=False, validators=[
                                  MinValueValidator(-90), MaxValueValidator(90)])
    date = models.DateField(auto_now=True)

class Trip(models.Model):
    name = models.CharField(null=False, blank=False, max_length=50)
    imo = models.IntegerField(null=False, blank=False, unique=True)
    trip_date = models.DateField(null=False, blank=False)
    submit_date = models.DateField(auto_now=True)
    origin_port =  models.ForeignKey(Port, on_delete=models.PROTECT, related_name='origin')
    dest_port = models.ForeignKey(Port, on_delete=models.PROTECT , related_name='destination')

ports/forms.py
from django import forms
from django.forms import ModelForm
from ports.models import Port, Trip


class PortForm(ModelForm):
    class Meta:
        model = Port
        fields = ['name', 'temp', 'latitude', 'longitude']

class TripForm(ModelForm):
    class Meta:
        model = Trip
        fields = ['name', 'imo', 'trip_date', 'origin_port','dest_port']

ports/views.py
from distutils.log import error
from logging import exception
from django.shortcuts import render, redirect
from ports.models import Port, Trip
from ports.forms import PortForm, TripForm
from django.contrib import messages
from django.urls import reverse
from django.db.models import Count

from django.http import HttpResponse, HttpResponseRedirect

def get_home_view(request):
    return render(request, template_name='home.html')

######## PORTS

def get_ports_view(request):
    ports = Port.objects.all()
    return render(request, 'ports.html', {
        'ports': ports
    })


def add_port_page(request):
    if request.method == 'GET':
        form = PortForm()
    else:
        form = PortForm(request.POST)
        if form.is_valid():
            port = form.save()
            port.save()
            return redirect(get_ports_view)
        else:
            messages.error(request, form.errors)
            #  TODO add error to event

            return render(request, template_name='add_port_page.html', context={'port_form': form.cleaned_data})

    return render(request, template_name='add_port_page.html')


def add_port_view(request):
    ports = Port.objects.all()
    if request.method == 'GET':
        form = PortForm()
    else:
        form = PortForm(request.POST)
        if form.is_valid():
            port = form.save()
            port.save()
        else:
            messages.error(request, form.errors)

            return render(request, template_name='ports.html', context={'ports': ports, 'port_form': form.cleaned_data})

    return render(request, template_name='ports.html', context={'ports': ports, 'port_form': form.cleaned_data})

def upload_csv_page(request):
    data = {}
    if "GET" == request.method:
        return render(request, "upload_csv.html", data)
    # if not GET, then proceed
    try:
        csv_file = request.FILES["csv_file"]
        if not csv_file.name.endswith('.csv'):
            messages.error(request,'File is not CSV type')
            return HttpResponseRedirect(reverse("upload_csv_page"))
        #if file is too large, return
        if csv_file.multiple_chunks():
            messages.error(request,"Uploaded file is too big (%.2f MB)." % (csv_file.size/(1000*1000),))
            return HttpResponseRedirect(reverse("upload_csv_page"))

        file_data = csv_file.read().decode("utf-8")        

        lines = file_data.split("\n")
        #loop over the lines and save them in db. If error , store as string and then display
        fine = True
        for line in lines:                        
            fields = line.split(",")
            data_dict = {}
            data_dict["name"] = fields[0]
            data_dict["temp"] = fields[1]
            data_dict["latitude"] = fields[2]
            data_dict["longitude"] = fields[3]
            try:
                form = PortForm(data_dict)
                if form.is_valid():
                    form.save()
                else:
                    messages.error(request, form.errors.as_json())
                    fine = False
            except Exception as e:
                messages.error(request,"Unable to add port. "+repr(e))
                pass
    except Exception as e:
        messages.error(request,"Unable to upload file. "+repr(e))
    if fine:
        return redirect(get_ports_view)
    return HttpResponseRedirect(reverse("upload_csv_page"))



def edit_port(request,id):
    port = Port.objects.get(pk=id)

    if request.method == 'GET':
            form = PortForm(instance=Port(port))
            return render(request, template_name='edit_port.html', context={'port':port, 'port_form': form})
    else:
        # try:
        form = PortForm(request.POST, instance=port)
        if form.is_valid():
            tform = form.save(commit=False)
            port = form.save()
            port.save()
            return redirect(get_ports_view)
        else:
            messages.error(request, form.errors)
            return render(request, template_name='edit_port.html', context={'port':port, 'port_form': form.data})
        # except:
        #     return redirect(get_ports_view)

    return redirect(get_ports_view)



def del_port(request,id):
    try:
        port = Port.objects.get(id=id)
        port.delete()
        return redirect(get_ports_view)
    except:
        return redirect(get_ports_view)

######## TRIPS

def get_trips_view(request):
    trips = Trip.objects.all()
    ports = Port.objects.all()
    return render(request, template_name='trips.html', context={
        'trips': trips, 'ports': ports
    })


def add_trip_page(request):
    ports = Port.objects.all()
    if request.method == 'GET':
        form = TripForm()
    else:
        form = TripForm(request.POST)
        if form.is_valid():
            trip = form.save()
            trip.save()
            return redirect(get_trips_view)
        else:
            messages.error(request, form.errors)
            #  TODO add error to event

            return render(request, template_name='add_trip_page.html', context={'trip_form': form.cleaned_data, 'ports': ports})

    return render(request, template_name='add_trip_page.html')


def add_trip_view(request):
    trips = Trip.objects.all()
    ports = Port.objects.all()
    if request.method == 'GET':
        form = TripForm()
    else:
        form = TripForm(request.POST)
        if form.is_valid():
            trip = form.save()
            trip.save()
        else:
            messages.error(request, form.errors)

            return render(request, template_name='trips.html', context={'trips': trips, 'trip_form': form.cleaned_data, 'ports': ports})

    return render(request, template_name='trips.html', context={'trips': trips, 'trip_form': form.cleaned_data, 'ports': ports})


def edit_trip(request,id):
    trip = Trip.objects.get(pk=id)

    if request.method == 'GET':
            form = TripForm(instance=Trip(trip))
            return render(request, template_name='edit_trip.html', context={'trip':trip, 'trip_form': form})
    else:
        # try:
        form = TripForm(request.POST, instance=trip)
        if form.is_valid():
            tform = form.save(commit=False)
            trip = form.save()
            trip.save()
            return redirect(get_trips_view)
        else:
            messages.error(request, form.errors)
            return render(request, template_name='edit_trip.html', context={'trip':trip, 'trip_form': form.data})
        # except:
        #     return redirect(get_trips_view)

    return redirect(get_trips_view)



def del_trip(request,id):
    try:
        trip = Trip.objects.get(id=id)
        trip.delete()
        return redirect(get_trips_view)
    except:
        return redirect(get_trips_view)


################
import json
def get_plot_view(request):
    # trips = Trip.objects.all()
    # ports = Port.objects.all()
    counts = Port.objects.annotate(origin_port_c=Count('origin', distinct=True), dest_port_c=Count('destination', distinct=True))
    # counts = json.dumps(counts)
    return render(request, template_name='plots.html', context={
        'counts':counts
    })

templates/add_port_page.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  {% load static %}
  <link href="{% static 'css/edit-style.css' %}" type="text/css" rel="stylesheet">

  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css'
    crossorigin="anonymous">
  <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet">
  <script src="https://kit.fontawesome.com/b5bc6a9427.js" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

  <title>{% block title %}Add Port{% endblock %}</title>
</head>

{% if messages %}
<div class="ctrl-panel2">
  <h3> Something Went Wrong </h3>
  {% for message in messages %}
  {{ message }}
  {% endfor %}
</div>
{% endif %}

<form action="/add_port_page" method="post">
  {% csrf_token %}
  <div class="group">
      <input type="text" class="form-control" name="name" maxlength="50" required="" id="id_name"
          value="{{ port_form.name }}"> <span class="highlight"></span><span class="bar"></span>
      <label for="id_name"> Name:</label>
  </div>
  <div class="group">
      <input type="text" class="form-control" name="temp" maxlength="10" required="" id="id_temp"
          value="{{ port_form.temp }}"> <span class="highlight"></span><span class="bar"></span>
      <label for="id_temp"> Temp:</label>
  </div>
  <div class="group">
      <input type="latitude" class="form-control" name="latitude" maxlength="100" required="" id="id_latitude"
          value="{{ port_form.latitude }}"><span class="highlight"></span><span class="bar"></span>
      <label for="id_latitude"> Latitude:</label>
  </div>
  <div class="group">
    <input type="longitude" class="form-control" name="longitude" maxlength="100" required="" id="id_longitude"
        value="{{ port_form.longitude }}"><span class="highlight"></span><span class="bar"></span>
    <label for="id_longitude"> Longitude:</label>
</div>
  <div class="d-grid gap-2">
      <button type="submit" class="btn btn-danger" value="Submit">Submit</button>
      <button type="button" onclick="history.back()" class="btn btn-secondary" data-bs-dismiss="modal">Back</button>
    </div>


</form>

{% block script %}

<script src="{% static 'script/edit-port-script.js' %}"></script>

{% load static %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
crossorigin="anonymous"></script>

{% endblock %}

<!-- <script type="text/javascript">window.$crisp = []; window.CRISP_WEBSITE_ID = "";
(function () {
  d = document; s = d.createElement("script");
  s.src = "https://client.crisp.chat/l.js"; s.async = 1;
  d.getElementsByTagName("head")[0].appendChild(s);
})();
</script> -->

</body>

</html>

templates/add_trip_page.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  {% load static %}
  <link href="{% static 'css/edit-style.css' %}" type="text/css" rel="stylesheet">

  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css'
    crossorigin="anonymous">
  <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet">
  <script src="https://kit.fontawesome.com/b5bc6a9427.js" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

  <title>{% block title %}Add Port{% endblock %}</title>
</head>

{% if messages %}
<div class="ctrl-panel2">
  <h3> Something Went Wrong </h3>
  {% for message in messages %}
  {{ message }}
  {% endfor %}
</div>
{% endif %}

<form action="/add_port_page" method="post">
  {% csrf_token %}
  <div class="group">
      <input type="text" class="form-control" name="name" maxlength="50" required="" id="id_name"
          value="{{ port_form.name }}"> <span class="highlight"></span><span class="bar"></span>
      <label for="id_name"> Name:</label>
  </div>
  <div class="group">
      <input type="text" class="form-control" name="imo" maxlength="10" required="" id="id_imo"
          value="{{ port_form.imo }}"> <span class="highlight"></span><span class="bar"></span>
      <label for="id_imo"> IMO:</label>
  </div>
  <div class="group">
      <input type="trip_date" class="form-control" name="trip_date" maxlength="100" required="" id="id_trip_date"
          value="{{ port_form.trip_date }}"><span class="highlight"></span><span class="bar"></span>
      <label for="id_trip_date"> Trip Date:</label>
  </div>
  <div class="group">
    <input type="origin_port" class="form-control" name="origin_port" maxlength="100" required="" id="id_origin_port"
        value="{{ port_form.origin_port }}"><span class="highlight"></span><span class="bar"></span>
    <label for="id_origin_port"> Origin:</label>
  </div>
  <div class="group">
    <input type="dest_port" class="form-control" name="dest_port" maxlength="100" required="" id="id_dest_port"
        value="{{ port_form.dest_port }}"><span class="highlight"></span><span class="bar"></span>
    <label for="id_dest_port"> Destination:</label>
  </div>
  <div class="d-grid gap-2">
      <button type="submit" class="btn btn-danger" value="Submit">Submit</button>
      <button type="button" onclick="history.back()" class="btn btn-secondary" data-bs-dismiss="modal">Back</button>
    </div>


</form>

{% block script %}

<script src="{% static 'script/edit-port-script.js' %}"></script>

{% load static %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
crossorigin="anonymous"></script>

{% endblock %}

<!-- <script type="text/javascript">window.$crisp = []; window.CRISP_WEBSITE_ID = "";
(function () {
  d = document; s = d.createElement("script");
  s.src = "https://client.crisp.chat/l.js"; s.async = 1;
  d.getElementsByTagName("head")[0].appendChild(s);
})();
</script> -->

</body>

</html>

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  {% load static %}
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css'
    crossorigin="anonymous">
  <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet">
  <script src="https://kit.fontawesome.com/b5bc6a9427.js" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <title>{% block title %}Django Simple{% endblock %}</title>
</head>

<body>
  <!-- <nav class="navbar navbar-dark bg-primary flex-nav-bar"> -->
  <nav class="navbar navbar-expand-custom navbar-mainbg">
    <a class="navbar-brand navbar-logo" href="/">Django Simple Task</a>
    <button class="navbar-toggler" type="button" aria-controls="navbarSupportedContent" aria-expanded="false"
      aria-label="Toggle navigation">
      <i class="fas fa-bars text-white"></i>
    </button>

    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <div class="hori-selector">
          <div class="left"></div>
          <div class="right"></div>
        </div>
        <li class="nav-item {% if 'ports' in request.path %} active{% endif %}">
          <a class="nav-link" href="{% url 'ports' %}"><i class="fa-solid fa-anchor"></i>Ports</a>
        </li>
        <li class="nav-item {% if 'trips' in request.path %} active{% endif %}">
          <a class="nav-link" href="{% url 'trips' %}"><i class="fa-solid fa-ship"></i>Trips</a>
        </li>
        <li class="nav-item {% if 'plots' in request.path %} active{% endif %}">
          <a class="nav-link" href="{% url 'plots' %}"><i class="fa-solid fa-chart-simple"></i>Plots</a>
        </li>
      </ul>
    </div>

  </nav>
  <main>
    {% block content %}
    {% endblock %}
  </main>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
    crossorigin="anonymous"></script>
  <script src="{% static 'script/nav-script.js' %}"></script>



  {% block script %}
  {% endblock %}
</body>

</html>

templates/edit_port.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  {% load static %}
  <link href="{% static 'css/edit-style.css' %}" type="text/css" rel="stylesheet">

  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css'
    crossorigin="anonymous">
  <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet">
  <script src="https://kit.fontawesome.com/b5bc6a9427.js" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

  <title>{% block title %}Add Port{% endblock %}</title>
</head>

{% if messages %}
<div class="ctrl-panel2">
  <h3> Something Went Wrong </h3>
  {% for message in messages %}
  {{ message }}
  {% endfor %}
</div>
{% endif %}

<hgroup>
  <h1>Edit Port {{ port.name }} PID. {{ port.id }}
      <div class="alert alert-danger" role="alert">
          Please be cautious.
      </div>
</hgroup>

<form action="/edit_port/{{ port.id }}" method="post">
  {% csrf_token %}
  <div class="group">
      <input type="text" class="form-control used" name="name" maxlength="50" required="" id="id_name"
          value="{{ port.name }}"> <span class="highlight"></span><span class="bar"></span>
      <label for="id_name"> Name:</label>
  </div>
  <div class="group">
      <input type="text" class="form-control used" name="temp" maxlength="10" required="" id="id_temp"
          value="{{ port.temp }}"> <span class="highlight"></span><span class="bar"></span>
      <label for="id_temp"> Temp:</label>
  </div>
  <div class="group">
      <input type="latitude" class="form-control used" name="latitude" maxlength="100" required="" id="id_latitude"
          value="{{ port.latitude }}"><span class="highlight"></span><span class="bar"></span>
      <label for="id_latitude"> Latitude:</label>
  </div>
  <div class="group">
    <input type="longitude" class="form-control used" name="longitude" maxlength="100" required="" id="id_longitude"
        value="{{ port.longitude }}"><span class="highlight"></span><span class="bar"></span>
    <label for="id_longitude"> Longitude:</label>
</div>
  <div class="d-grid gap-2">
      <button type="submit" class="btn btn-danger" value="Submit">Submit</button>
      <button type="button" onclick="history.back()" class="btn btn-secondary" data-bs-dismiss="modal">Back</button>
    </div>


</form>

{% block script %}

<script src="{% static 'script/edit-port-script.js' %}"></script>

{% load static %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
crossorigin="anonymous"></script>

{% endblock %}

<!-- <script type="text/javascript">window.$crisp = []; window.CRISP_WEBSITE_ID = "";
(function () {
  d = document; s = d.createElement("script");
  s.src = "https://client.crisp.chat/l.js"; s.async = 1;
  d.getElementsByTagName("head")[0].appendChild(s);
})();
</script> -->

</body>

</html>

templates/home.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

<h1>Use Menu / NavBar </h1>

{% endblock %}

templates/trips.html
<!-- imolates/trips.html-->
{% extends 'base.html' %}

{% block title %}trips{% endblock %}

{% block content %}

{% load static %}

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js" integrity="sha256-+C0A5Ilqmu4QcSPxrlGpaZxJ04VjsRjKu+G82kl5UJk=" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css" integrity="sha256-ze/OEYGcFbPRmvCnrSeKbRTtjG4vGLHXgOqsyLFTRjg=" crossorigin="anonymous" />

{% if messages %}
<div class="ctrl-panel2">
  <h3> Something Went Wrong </h3>
  {% for message in messages %}
  {{ message }}
  {% endfor %}
</div>
{% endif %}

<div class="container" style="padding-bottom: 20px;">
  <div class="btn-toolbar" role="toolbar">
    <div class="btn-group btn-group-lg btn-group-justified btn-group-fill-height">
      <button type="button" class="btn btn-default port-reg-button" data-bs-toggle="modal"
        data-bs-target="#exampleModal" data-bs-whatever=""> <strong>Add new trip</strong>
        <span>Same page</span> </button>
      <a href="{% url 'add_trip_page' %}" class="btn btn-success port-reg-button" role="button">
        <strong>Add new trip</strong>
        <span>Other page</span>
      </a>
    </div>
  </div>
</div>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add New trip</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        {% if messages %}
        {% for message in messages %}
        {{ message }}
        {% endfor %}
        {% endif %}
        <form action="/add_trip" method="post">
          {% csrf_token %}
          <div class="mb-3">
            <label for="id_name" class="col-form-label">Vessel Name:</label>
            <input type="text" class="form-control" name="name" maxlength="50" required="" id="id_name"
              value="{{ trip_form.name }}">
          </div>
          <label for="id_imo" class="col-form-label">IMO:</label>
          <div class="input-group mb-3">
            <input type="number" class="form-control" name="imo" maxlength="10" required="" id="id_imo"
              value="{{ trip_form.imo }}">
          </div>
          <div class="mb-3">
            <label for="id_trip_date" class="col-form-label">Date:</label>
            <input type="date" class="form-control" name="trip_date" maxlength="10" required="" id="id_trip_date"
              value="{{ trip_form.trip_date }}">
          </div>
          <div class="mb-3">
            <label for="id_origin_port" class="col-form-label">Origin:</label>
            <select  name="origin_port" id="id_origin_port">
              {% for port in ports %}
              <option value="{{ port.id }}">{{ port.name }}</option>
              {% endfor %}
            <select>
          </div>
          <div class="mb-3">
            <label for="id_dest_port" class="col-form-label">Destination:</label>
            <select  name="dest_port" id="id_dest_port">
              {% for port in ports %}
              <option value="{{ port.id }}">{{ port.name }}</option>
              {% endfor %}
            <select>
          </div>
          <!-- <div class="mb-3">
            <label for="id_dest_port" class="col-form-label">Destination:</label>
            <input type="text" class="form-control" name="dest_port" maxlength="50" required="" id="id_dest_port"
              value="{{ trip_form.dest_port }}">
          </div> -->
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary" value="Submit">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<table class="table trip-table" id="trip-table">
  <thead>
    <tr>
      <th scope="col"><span class="table-column"> PID <i class="caret"></span></th>
      <th scope="col"><span class="table-column"> trip Name <i class="caret"></span></th>
      <th scope="col"><span class="table-column"> IMO <i class="caret"></span></th>
      <th scope="col"><span class="table-column"> Origin <i class="caret"></span></th>
      <th scope="col"><span class="table-column"> Destination <i class="caret"></span></th>
      <th scope="col"><span class="table-column"> Trip Date <i class="caret"></span></th>
      <th scope="col"><span class="table-column"> Create Date <i class="caret"></span></th>
    </tr>
  </thead>
  <tbody id="trip-table-body">
    {% for trip in trips %}
    <tr>
      <th scope="row">{{ trip.id }}</th>
      <td>{{ trip.name }}</td>
      <td>{{ trip.imo }}</td>
      <td>{{ trip.origin_port.name }}</td>
      <td>{{ trip.dest_port.name }}<t/d>
      <td>{{ trip.trip_date }}</td>
      <td>{{ trip.submit_date }}</td>
    {% endfor %}
  </tbody>
  <tfoot>
    <tr>
      <th scope="col"><span class="table-column"> PID <i class="caret"></span></th>
      <th scope="col"><span class="table-column"> trip Name <i class="caret"></span></th>
      <th scope="col"><span class="table-column"> IMO <i class="caret"></span></th>
      <th scope="col"><span class="table-column"> Origin <i class="caret"></span></th>
      <th scope="col"><span class="table-column"> Destination <i class="caret"></span></th>
      <th scope="col"><span class="table-column"> Trip Date <i class="caret"></span></th>
      <th scope="col"><span class="table-column"> Create Date <i class="caret"></span></th>
    </tr>
  </tfoot>
</table>

{% endblock %}
{% block script %}
{% load static %}
<script src="{% static 'script/trip-table-script.js' %}"></script>

{% endblock %}